apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new-deployment
  labels:
    app: nginx-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html   # NGINX default web root
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
